fix: fix pickling error on exit
the error reports:

> _pickle.PicklingError: can't pickle `<class 'list'>: import of module 'builtins' failed.

it relates this [issue](https://bugs.python.org/issue42935), the answer suggests us to use `atexit` instead of try catch on the close event.